// <auto-generated />
using System;
using API.ProjetoCursosIdioma.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.ProjetoCursosIdioma.Migrations
{
    [DbContext(typeof(PCI_DbContext))]
    [Migration("20260715132900_AlunoTurma Relationship_Fix")]
    partial class AlunoTurmaRelationship_Fix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.ProjetoCursosIdioma.Models.Domain.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("API.ProjetoCursosIdioma.Models.Domain.AlunoTurma", b =>
                {
                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TurmaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AlunoId", "TurmaId");

                    b.HasIndex("TurmaId");

                    b.ToTable("AlunoTurmas");
                });

            modelBuilder.Entity("API.ProjetoCursosIdioma.Models.Domain.NivelTurma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NivelTurmas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20ef9ed7-a2de-4b12-afbc-d7e95a2bdf1e"),
                            Name = "Básico"
                        },
                        new
                        {
                            Id = new Guid("ab10d5c3-0dac-4087-a6ec-50871b732e96"),
                            Name = "Intermediário"
                        },
                        new
                        {
                            Id = new Guid("9fd3436d-c6e3-4c54-b2ae-6769659c1644"),
                            Name = "Avançado"
                        });
                });

            modelBuilder.Entity("API.ProjetoCursosIdioma.Models.Domain.Turma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnoLetivo")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("NivelTurmaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NumeroTurma")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NivelTurmaId");

                    b.HasIndex("Name", "NivelTurmaId", "AnoLetivo", "NumeroTurma")
                        .IsUnique();

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("API.ProjetoCursosIdioma.Models.Domain.AlunoTurma", b =>
                {
                    b.HasOne("API.ProjetoCursosIdioma.Models.Domain.Aluno", "Aluno")
                        .WithMany("AlunoTurmas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.ProjetoCursosIdioma.Models.Domain.Turma", "Turma")
                        .WithMany("AlunoTurmas")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("API.ProjetoCursosIdioma.Models.Domain.Turma", b =>
                {
                    b.HasOne("API.ProjetoCursosIdioma.Models.Domain.NivelTurma", "NivelTurma")
                        .WithMany()
                        .HasForeignKey("NivelTurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelTurma");
                });

            modelBuilder.Entity("API.ProjetoCursosIdioma.Models.Domain.Aluno", b =>
                {
                    b.Navigation("AlunoTurmas");
                });

            modelBuilder.Entity("API.ProjetoCursosIdioma.Models.Domain.Turma", b =>
                {
                    b.Navigation("AlunoTurmas");
                });
#pragma warning restore 612, 618
        }
    }
}
